#!/usr/bin/env node

/**
 * KCO historical report exporter (/kco-export).
 *
 * Exported `global-stats.json` values are tracker-derived historical heuristics.
 * The legacy field `estimatedTokensSaved` is rendered only as estimated
 * historical unused-read volume. Runtime blocked-read savings live in a
 * separate ledger and are not inferred from these cross-session aggregates.
 */

import { writeFileSync } from 'fs';
import { basename, join } from 'path';
import {
  GLOBAL_STATS_FILE, EXPORTS_DIR,
  formatTokens, loadJSON, ensureDataDirs, isMainModule,
  getPricing, computeCost, formatCost,
} from './utils.js';

ensureDataDirs();

function historicalSummary(stats) {
  const total = stats.totalTokensTracked || 0;
  const unused = stats.estimatedTokensSaved || 0;
  const pct = total > 0 ? Math.min(100, Math.round((unused / total) * 100)) : 0;
  return { total, unused, pct };
}

function exportMarkdown() {
  const stats = loadJSON(GLOBAL_STATS_FILE);
  if (!stats || stats.totalSessions === 0) {
    console.log('No data to export.');
    return;
  }

  const { total, unused, pct } = historicalSummary(stats);
  const pricing = getPricing();
  const date = new Date().toISOString().split('T')[0];
  let md = `# KCO Historical Context Report — ${date}\n\n`;
  md += `> **Evidence class: ESTIMATED HISTORICAL HEURISTIC.** `;
  md += `Estimated historical unused-read volume is not the runtime blocked-read savings ledger and is not a direct measurement of Kimi subscription quota.\n\n`;

  md += `## Overview\n\n`;
  md += `| Metric | Value |\n|---|---:|\n`;
  md += `| Sessions tracked | ${stats.totalSessions} |\n`;
  md += `| Total tracked token volume | ${formatTokens(total)} |\n`;
  md += `| Estimated historical unused-read volume | ${formatTokens(unused)} |\n`;
  md += `| Historical unused-read ratio | ${pct}% |\n`;
  md += `| Avg tracked tokens/session | ${formatTokens(stats.avgTokensPerSession || 0)} |\n`;
  md += `| Files read / edited | ${stats.totalFilesRead || 0} / ${stats.totalFilesEdited || 0} |\n`;
  if (pricing.input !== null) {
    const configured = formatCost(computeCost(unused, 'input'));
    if (configured) md += `| Historical unused-read volume at configured input rate | ~${configured} |\n`;
  }
  md += '\n';

  if (stats.topWastedFiles && stats.topWastedFiles.length) {
    md += `## Top Historical Unused-Read Files\n\n`;
    md += `| File | Estimated historical unused-read volume | Sessions |\n|---|---:|---:|\n`;
    for (const f of stats.topWastedFiles.slice(0, 10)) {
      md += `| \`${basename(f.fullPath || f.path || 'unknown')}\` | ~${formatTokens(f.totalTokensWasted || 0)} | ${f.sessions || 0} |\n`;
    }
    md += '\n';
  }

  if (stats.topUsefulFiles && stats.topUsefulFiles.length) {
    md += `## Top Historically Useful Files\n\n`;
    md += `| File | Edits | Reads | Sessions |\n|---|---:|---:|---:|\n`;
    for (const f of stats.topUsefulFiles.slice(0, 10)) {
      md += `| \`${basename(f.fullPath || f.path || 'unknown')}\` | ${f.totalEdits || 0} | ${f.totalReads || 0} | ${f.sessions || 0} |\n`;
    }
    md += '\n';
  }

  md += `## Interpretation\n\n`;
  md += `The estimated historical avoidable-read volume is an optimization-opportunity heuristic. `;
  md += `Use \`/kco\` for the separate runtime counterfactual ledger, which subtracts KCO's model-visible overhead.\n\n`;
  md += `---\n*Generated by kimi-context-optimizer (KCO) for Kimi Code CLI.*\n`;

  const outFile = join(EXPORTS_DIR, `report-${date}.md`);
  writeFileSync(outFile, md);
  console.log(`Exported to: ${outFile}`);
  return outFile;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function exportHTML() {
  const stats = loadJSON(GLOBAL_STATS_FILE);
  if (!stats || stats.totalSessions === 0) {
    console.log('No data to export.');
    return;
  }

  const { total, unused, pct } = historicalSummary(stats);
  const pricing = getPricing();
  const date = new Date().toISOString().split('T')[0];
  const configured = pricing.input !== null ? formatCost(computeCost(unused, 'input')) : null;
  const wastedRows = (stats.topWastedFiles || []).slice(0, 10).map((f) => `
    <tr><td><code>${escapeHtml(basename(f.fullPath || f.path || 'unknown'))}</code></td><td>~${escapeHtml(formatTokens(f.totalTokensWasted || 0))}</td><td>${f.sessions || 0}</td></tr>`).join('');
  const usefulRows = (stats.topUsefulFiles || []).slice(0, 10).map((f) => `
    <tr><td><code>${escapeHtml(basename(f.fullPath || f.path || 'unknown'))}</code></td><td>${f.totalEdits || 0}</td><td>${f.totalReads || 0}</td><td>${f.sessions || 0}</td></tr>`).join('');

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>KCO Context Dashboard</title>
<style>
body{font-family:system-ui,-apple-system,sans-serif;background:#0d1117;color:#c9d1d9;margin:0;padding:32px;line-height:1.55}main{max-width:960px;margin:auto}.note,.card,table{border:1px solid #30363d;border-radius:10px;background:#161b22}.note{padding:16px;border-left:4px solid #d29922}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px;margin:24px 0}.card{padding:18px}.label{color:#8b949e;font-size:12px;text-transform:uppercase}.value{font-size:28px;font-weight:700;margin-top:4px}table{width:100%;border-collapse:collapse;overflow:hidden;margin:12px 0 28px}th,td{padding:10px 12px;border-bottom:1px solid #30363d;text-align:left}th{color:#8b949e;font-size:12px;text-transform:uppercase}tr:last-child td{border-bottom:0}code{color:#79c0ff}small{color:#8b949e}h1{color:#58a6ff}h2{margin-top:32px}</style>
</head>
<body><main>
<h1>KCO Context Dashboard</h1>
<p><small>Generated ${date}</small></p>
<div class="note"><strong>Evidence class: ESTIMATED HISTORICAL HEURISTIC.</strong> Estimated historical unused-read volume is not the runtime blocked-read savings ledger and is not a direct measurement of Kimi subscription quota.</div>
<div class="cards">
  <div class="card"><div class="label">Sessions</div><div class="value">${stats.totalSessions}</div></div>
  <div class="card"><div class="label">Tracked token volume</div><div class="value">${escapeHtml(formatTokens(total))}</div></div>
  <div class="card"><div class="label">Estimated historical unused-read volume</div><div class="value">${escapeHtml(formatTokens(unused))}</div><small>${pct}% of tracked historical volume${configured ? ` · ~${escapeHtml(configured)} at configured input rate` : ''}</small></div></div>
  <div class="card"><div class="label">Files read / edited</div><div class="value">${stats.totalFilesRead || 0} / ${stats.totalFilesEdited || 0}</div></div>
</div>
${wastedRows ? `<h2>Top Historical Unused-Read Files</h2><table><tr><th>File</th><th>Estimated historical unused-read volume</th><th>Sessions</th></tr>${wastedRows}</table>` : ''}
${usefulRows ? `<h2>Top Historically Useful Files</h2><table><tr><th>File</th><th>Edits</th><th>Reads</th><th>Sessions</th></tr>${usefulRows}</table>` : ''}
<h2>Interpretation</h2>
<p>The estimated historical avoidable-read volume is an optimization-opportunity heuristic. Use <code>/kco</code> for the separate runtime counterfactual ledger, which subtracts KCO's model-visible overhead.</p>
</main></body></html>`;

  const outFile = join(EXPORTS_DIR, `report-${date}.html`);
  writeFileSync(outFile, html);
  console.log(`Exported to: ${outFile}`);
  return outFile;
}

function main() {
  const format = process.argv[2] || 'md';
  if (format === 'html') exportHTML();
  else exportMarkdown();
}

if (isMainModule(import.meta.url)) {
  try { main(); } catch (e) { console.error(`[kco] export error: ${e.message}`); process.exit(0); }
}

export { exportMarkdown, exportHTML, historicalSummary };
